### ISSUE TITLE
Documentation on how to use v-toaster in a browser

### ISSUE THREAD

**Issue by miseeger** [paliari/v-toaster#1]
Hi and first of all: Thank you for this cool component! 

When I tried to get it running by including it in a browser script, the documented way failed. It has to be  
_VToaster_ instead of _Toaster_ ;-)

```javascript
<script>
  Vue.use(VToaster, {timeout: 5000})
</script>
```

Cheers.

**Comment by paliari** [comment]
Thank you for the tip
