### ISSUE TITLE
unable to call v-toaster from interceptors.js

### ISSUE THREAD

**Issue by naresh-io** [paliari/v-toaster#3]

**Comment by paliari** [comment]
What is interceptor.js?
Send an example of your code.

**Comment by fabienmasson** [comment]
I also cannot use v-toaster from axios interceptor.

In my main.js :

axios.interceptors.response.use(
  function(response) {
    return response
  },
  function(error) {
    let myerror="Erreur: "+error
    console.log(myerror)
    this.$toaster.error("Erreur") 
    return Promise.reject(error)
  }
)

The message in toaster is {}

**Comment by tinohager** [comment]
I find a solution `Vue.prototype.$toaster.error("Some text");`

**Comment by paliari** [comment]
You can use `this.$toaster` only in a `Vue` component instance.
If you are trying to use in a service or another file, you can use like `Vue.toaster.error('some message')`
