### ISSUE TITLE
Use toaster in main.js with interceptors

### ISSUE THREAD

**Issue by tinohager** [paliari/v-toaster#7]
How is the correct way to use the toaster in the main.js?

I want use [interceptors](https://github.com/axios/axios#interceptors) for global error handling?
Is this the only solution? `Vue.prototype.$toaster.error("Some text");`

**Comment by paliari** [comment]
You can use `this.$toaster` only in a `Vue` component instance.
If you are trying to use in a service or another file, you can use like `Vue.toaster.error('some message')`
